import { test, expect } from '@playwright/test'

test('Chrome journey: login, recon, Hydra, bank, refresh, flag, restart, cleanup', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Unlock' }).click()
  await expect(page.getByLabel('Terminal command')).toBeVisible()
  const command = page.getByLabel('Terminal command')
  await command.fill('nmap 10.8.0.22'); await command.press('Enter')
  await expect(page.locator('.lab-tray .done').filter({ hasText: 'Scan' })).toBeVisible()
  await command.fill('hydra -l bisha -P wordlist.txt 10.8.0.22 http-post-form "/login:username=^USER^&password=^PASS^:Invalid"')
  await command.press('Enter')
  await expect(page.locator('.qterm-out')).toContainText('password: bisha')
  await page.getByRole('button', { name: 'Firefox ESR', exact: true }).click()
  await page.getByLabel('Bank username').fill('bisha')
  await page.getByLabel('Bank password').fill('bisha')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const flag = await page.locator('.portal-app code').innerText()
  expect(flag).toMatch(/^CYBERPOD\{/)
  await page.reload()
  await page.getByRole('button', { name: 'Firefox ESR', exact: true }).click()
  await expect(page.locator('.portal-app code')).toHaveText(flag)
  await page.getByLabel('Flag', { exact: true }).fill(flag)
  await page.getByRole('button', { name: 'Submit flag', exact: true }).click()
  await expect(page.locator('.lab-tray')).toContainText('Score 100/100')
  await page.getByRole('button', { name: 'Restart lab' }).click()
  await expect(page.locator('.lab-tray')).toContainText('Score 0/100')
  await page.getByRole('button', { name: 'End lab' }).click()
  await expect(page.getByRole('button', { name: 'Unlock' })).toBeVisible()
  expect(errors).toEqual([])
})

test('phone viewport can reach terminal, bank login and flag controls', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Unlock' }).click()
  await page.getByLabel('Terminal command').fill('help')
  await page.getByLabel('Terminal command').press('Enter')
  await page.getByLabel('Bank username').fill('bisha')
  await page.getByLabel('Bank password').fill('bisha')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.portal-app code')).toContainText('CYBERPOD{')
  await page.getByLabel('Flag', { exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByLabel('Flag', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
