import { test, expect } from '@playwright/test'

async function unlock(page) {
  await page.goto('/')
  await expect(page.getByLabel('Password', { exact: true })).toHaveValue('')
  await page.getByLabel('Password', { exact: true }).fill('bisha')
  await page.getByRole('button', { name: 'Unlock' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.lab-tray')).toContainText('Score 0/100')
}

async function openBank(page) {
  await page.locator('.desk-icons').getByRole('button', { name: 'Firefox ESR', exact: true }).click()
  await expect(page.getByLabel('Browser address')).toHaveValue('')
  await page.getByLabel('Browser address').fill('http://10.8.0.22/login')
  await page.getByRole('button', { name: 'Go', exact: true }).click()
}

test('Chrome journey: login, recon, Hydra, bank, refresh, flag, restart, cleanup', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await unlock(page)
  await page.locator('.desk-icons').getByRole('button', { name: 'Terminal', exact: true }).click()
  await expect(page.getByLabel('Terminal command')).toBeVisible()
  const command = page.getByLabel('Terminal command')
  await command.fill('nmap 10.8.0.22'); await command.press('Enter')
  await expect(page.locator('.lab-tray .done').filter({ hasText: 'Scan' })).toBeVisible()
  await command.fill('hydra -l bisha -P wordlist.txt 10.8.0.22 http-post-form "/login:username=^USER^&password=^PASS^:Invalid"')
  await command.press('Enter')
  await expect(page.locator('.qterm-out')).toContainText('password: bisha')
  await openBank(page)
  await expect(page.getByLabel('Bank password')).toHaveValue('')
  await page.getByLabel('Bank username').fill('bisha')
  await page.getByLabel('Bank password').fill('bisha')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const flag = await page.locator('.portal-app code').innerText()
  expect(flag).toMatch(/^CYBERPOD\{/)
  await page.reload()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await openBank(page)
  await expect(page.locator('.portal-app code')).toHaveText(flag)
  await page.getByRole('button', { name: 'Close Mozilla Firefox ESR', exact: true }).click()
  await page.getByLabel('Flag', { exact: true }).fill(flag)
  await page.getByRole('button', { name: 'Submit flag', exact: true }).click()
  await expect(page.locator('.lab-tray')).toContainText('Score 100/100')
  await page.getByRole('button', { name: 'Restart lab' }).click()
  await expect(page.locator('.lab-tray')).toContainText('Score 0/100')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'End lab' }).click()
  await expect(page.getByRole('button', { name: 'Unlock' })).toBeVisible()
  await expect(page.getByLabel('Password', { exact: true })).toHaveValue('')
  expect(errors).toEqual([])
})

test('phone viewport can reach terminal, bank login and flag controls', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await unlock(page)
  await page.locator('.desk-icons').getByRole('button', { name: 'Terminal', exact: true }).click()
  await page.getByLabel('Terminal command').fill('help')
  await page.getByLabel('Terminal command').press('Enter')
  await page.getByRole('button', { name: 'Close bisha@kali: ~', exact: true }).click()
  await openBank(page)
  await page.getByLabel('Bank username').fill('bisha')
  await page.getByLabel('Bank password').fill('bisha')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.portal-app code')).toContainText('CYBERPOD{')
  await page.getByRole('button', { name: 'Close Mozilla Firefox ESR', exact: true }).click()
  await page.getByLabel('Flag', { exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByLabel('Flag', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

for (const width of [1280, 900]) {
  test(`manual window controls and two-axis dragging at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 800 })
    await unlock(page)
    await page.locator('.desk-icons').getByRole('button', { name: 'Terminal', exact: true }).click()
    const terminal = page.locator('[data-window="terminal"]')
    await expect(terminal).toBeVisible()
    const original = await terminal.boundingBox()
    const bar = await terminal.locator('.xfwm-bar').boundingBox()
    await page.mouse.move(bar.x + 100, bar.y + 14)
    await page.mouse.down()
    await page.mouse.move(bar.x + 160, bar.y - 86, { steps: 8 })
    await page.mouse.up()
    const moved = await terminal.boundingBox()
    expect(moved.x).toBeCloseTo(original.x + 60, 0)
    expect(moved.y).toBeCloseTo(original.y - 100, 0)

    await page.getByLabel('Terminal command').fill('echo still here')
    await terminal.getByRole('button', { name: 'Minimize bisha@kali: ~', exact: true }).click()
    await expect(terminal).toBeHidden()
    await page.getByRole('button', { name: 'Show Terminal', exact: true }).click()
    await expect(page.getByLabel('Terminal command')).toHaveValue('echo still here')
    expect((await terminal.boundingBox()).x).toBeCloseTo(moved.x, 0)

    await terminal.getByRole('button', { name: 'Maximize bisha@kali: ~', exact: true }).click()
    expect((await terminal.boundingBox()).width).toBeCloseTo(width - 16, 0)
    await terminal.getByRole('button', { name: 'Restore bisha@kali: ~', exact: true }).click()
    expect((await terminal.boundingBox()).x).toBeCloseTo(moved.x, 0)
    expect((await terminal.boundingBox()).width).toBeCloseTo(moved.width, 0)
    await terminal.getByRole('button', { name: 'Close bisha@kali: ~', exact: true }).click()
    await expect(terminal).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Show Terminal', exact: true })).toHaveCount(0)
    await page.locator('.desk-icons').getByRole('button', { name: 'Terminal', exact: true }).click()
    expect((await terminal.boundingBox()).x).toBeCloseTo(moved.x, 0)
    await terminal.getByRole('button', { name: 'Close bisha@kali: ~', exact: true }).click()

    for (const [label, title] of [['Firefox ESR', 'Mozilla Firefox ESR'], ['Lab Net', 'lab-net 10.8.0.0/24'], ['Home', 'Home'], ['Lab Notes', 'lab-notes.txt']]) {
      await page.locator('.desk-icons').getByRole('button', { name: label, exact: true }).click()
      const app = page.getByRole('dialog', { name: title, exact: true })
      await expect(app).toBeVisible()
      await app.getByRole('button', { name: `Close ${title}`, exact: true }).click()
      await expect(app).toHaveCount(0)
    }
    await expect(page.locator('.lab-tray')).toContainText('Score 0/100')

    await page.getByRole('button', { name: 'Applications', exact: true }).click()
    await page.getByRole('button', { name: 'QTerminal', exact: true }).click()
    await page.setViewportSize({ width: 390, height: 600 })
    await expect(terminal).toHaveCSS('width', '374px')
    const small = await terminal.boundingBox()
    expect(small.x).toBeGreaterThanOrEqual(0)
    expect(small.y).toBeGreaterThanOrEqual(30)
    expect(small.x + small.width).toBeLessThanOrEqual(390)
    expect(small.y + small.height).toBeLessThanOrEqual(562)
    await terminal.getByRole('button', { name: 'Close bisha@kali: ~', exact: true }).click()
  })
}
