import { test, expect } from '@playwright/test'

test('browser uses the real student API across refresh and lifecycle changes', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('Username', { exact: true }).fill('demo@cyberpod.local')
  await page.getByLabel('Password', { exact: true }).fill('CyberPodDemo123!')
  await page.getByRole('button', { name: 'Unlock' }).click()
  await page.getByRole('button', { name: 'Start Hydra Lab', exact: true }).click()
  await expect(page.locator('main')).toContainText('RUNNING')
  await expect(page.locator('main')).toContainText('API simulation')
  await page.getByLabel('Flag', { exact: true }).fill('wrong')
  await page.getByRole('button', { name: 'Submit flag', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('INCORRECT')
  await page.reload()
  await expect(page.locator('main')).toContainText('RUNNING')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.locator('main')).toContainText('STOPPED')
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(page.locator('main')).toContainText('RUNNING')
  await page.getByRole('button', { name: 'Restart lab', exact: true }).click()
  await expect(page.locator('main')).toContainText('Score 0/100')
  await page.getByRole('button', { name: 'End lab', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Labs', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Unlock' })).toBeVisible()
  expect(errors).toEqual([])
})
